"""Add last_updated and progress_percentage columns to Resource model

Revision ID: 4d9d838dcec7
Revises: ad3e724b39e9
Create Date: 2025-04-22 22:08:12.345678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9d838dcec7'
down_revision = 'ad3e724b39e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress_percentage', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('progress_percentage')

    # ### end Alembic commands ###
