"""add date_joined column to user table

Revision ID: 82da03f1fb62
Revises: d0192ac355b4
Create Date: 2025-04-23 18:33:12.476767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82da03f1fb62'
down_revision = 'd0192ac355b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('user', sa.Column('date_joined', sa.DateTime(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE \"user\" SET date_joined = CURRENT_TIMESTAMP WHERE date_joined IS NULL")
    
    # Then make it non-nullable
    op.alter_column('user', 'date_joined', nullable=False)
    
    # Handle other column modifications
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.drop_column('date_joined')

    # ### end Alembic commands ###
