"""Add progress column to Resource model

Revision ID: ad3e724b39e9
Revises: 
Create Date: 2025-04-20 11:37:41.638421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3e724b39e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('progress', sa.String(length=50), nullable=False,server_default='Not Started'))
        # batch_op.drop_column('completed')
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
