"""Add type column to Resource model

Revision ID: d0192ac355b4
Revises: 4d9d838dcec7
Create Date: 2025-04-22 22:11:23.124476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0192ac355b4'
down_revision = '4d9d838dcec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=True))
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        # batch_op.drop_column('type')
        pass

    # ### end Alembic commands ###
