"""Add notes field to Resource model

Revision ID: ec939abe2ed1
Revises: multiple_urls_support
Create Date: 2025-05-11 22:25:51.080283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec939abe2ed1'
down_revision = 'multiple_urls_support'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
